version: '3.9'
services:
  api:
    build:
      context: .
    depends_on:
      - db
    links:
      - db
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - '8080:8080'
  db:
    image: postgres:14.5-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
