CREATE TABLE wallet (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    address             VARCHAR(64) UNIQUE NOT NULL,
    nonce               BIGINT NOT NULL,
    balance             DECIMAL(64, 20) NOT NULL,
    balance_on_hold     DECIMAL(64, 20) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT check_lowercase_address CHECK (LOWER(address) = address)
);

CREATE TABLE transaction (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    transaction_hash    VARCHAR(96) UNIQUE,
    status              VARCHAR(16) NOT NULL,
    block_confirmation  INT NOT NULL,
    from_address        VARCHAR(64) NOT NULL,
    to_address          VARCHAR(64) NOT NULL,
    amount              DECIMAL(64, 20) NOT NULL,
    nonce               BIGINT NOT NULL,
    block_hash          VARCHAR(96),
    block_number        BIGINT,
    ts                  TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT check_lowercase_hash CHECK (LOWER(transaction_hash) = transaction_hash)
);
